'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import Link from 'next/link';
import {PageHeader} from '@/components/app/page-header';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {backendRequest} from '@/lib/workflow/backend-client';
import type {WorkflowDocument} from '@/lib/workflow/universal';
import styles from './schedules.module.css';
import dialogStyles from './workflow.module.css';
type ReleaseRow={id:string;title:string;revision:number;created_at:string;store_name:string;node_count:number;active_runs:number;run_count:number;active_schedules:number;schedule_count:number;deleted:boolean;can_delete:boolean};
type ReleaseList={results:ReleaseRow[];count:number;page:number;page_size:number};

function ReleaseDialog({row,confirm,busy,onClose,onDelete}:{row:ReleaseRow;confirm:boolean;busy:boolean;onClose:()=>void;onDelete:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[document,setDocument]=useState<WorkflowDocument|null>(null),[error,setError]=useState('');
 useEffect(()=>{const focus=window.document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>focus?.focus();},[]);
 useEffect(()=>{if(confirm)return;let active=true;backendRequest<{document:WorkflowDocument}>(`workflow-releases/${row.id}`).then(r=>{if(active)setDocument(r.document);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[row.id,confirm]);
 return createPortal(<dialog ref={ref} className={dialogStyles.dialog} aria-label={confirm?'删除冻结版本':'查看冻结流程'} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><header className={dialogStyles.dialogHeader}><div><h2>{confirm?'删除冻结版本':row.title}</h2><p>冻结版本 r{row.revision} · {row.store_name}</p></div><Button disabled={busy} onClick={onClose}>关闭</Button></header><div className={dialogStyles.dialogBody}>{confirm?<><p>删除后，此版本不能用于启动新运行或创建定时计划。可在“已删除”中恢复。</p><p>不会删除草稿、历史运行、已发布商品或发布凭据，也不会取消任何任务。暂停中的定时计划保留引用，恢复版本后才可重新启用。</p></>:<><p>这是整套流程的只读冻结快照，共 {row.node_count} 个节点。调整配置请回编辑器保存并冻结新版本。</p>{error&&<p role="alert">{error}</p>}{!document&&!error&&<p>正在读取冻结快照…</p>}<ol>{document?.nodes.map(n=><li key={n.id}><h3>{n.title}</h3><details><summary>查看冻结参数</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(n.binding.parameters,null,2)}</pre></details></li>)}</ol></>}</div>{confirm&&<footer className={dialogStyles.dialogFooter}><Button disabled={busy} onClick={onClose}>取消</Button><Button disabled={busy} variant="primary" onClick={onDelete}>{busy?'正在删除…':'确认删除此版本'}</Button></footer>}</dialog>,window.document.body);
}

export function WorkflowReleases(){
 const [view,setView]=useState<'active'|'deleted'>('active'),[page,setPage]=useState(1),[tick,setTick]=useState(0),[data,setData]=useState<ReleaseList|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dialog,setDialog]=useState<{row:ReleaseRow;confirm:boolean}|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError('');backendRequest<ReleaseList>(`workflow-releases?${new URLSearchParams({view,page:String(page)})}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active){setData(null);setError(e.message);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[view,page,tick]);
 async function change(row:ReleaseRow,restore=false){if(busy)return;setBusy(true);setError('');try{await backendRequest(`workflow-releases/${row.id}/lifecycle`,restore?'POST':'DELETE',{});setDialog(null);setMessage(restore?'版本已恢复；不会自动启用定时器或启动运行。':'版本已删除，可在“已删除”中恢复。历史和商品未删除。');setTick(n=>n+1);}catch(e){setDialog(null);setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 return <div className={styles.workspace}><PageHeader title="冻结版本" description="管理整个业务流程的配置快照。冻结后不随草稿变化，每次运行与定时计划都绑定具体版本。" actions={<><Link className="ui-button ui-button--secondary" href="/workflow/builder">工作流编辑器 ↗</Link><Link className="ui-button ui-button--secondary" href="/schedules">定时器 ↗</Link><Button disabled={loading||busy} onClick={()=>setTick(n=>n+1)}>刷新</Button></>}/><nav aria-label="冻结版本视图"><Button aria-pressed={view==='active'} variant={view==='active'?'primary':'ghost'} onClick={()=>{setView('active');setPage(1);setMessage('');}}>可用版本</Button><Button aria-pressed={view==='deleted'} variant={view==='deleted'?'primary':'ghost'} onClick={()=>{setView('deleted');setPage(1);setMessage('');}}>已删除</Button></nav>{(error||message)&&<p className={styles.notice} role={error?'alert':'status'}>{error||message}</p>}<section className={styles.list} aria-label="冻结流程版本列表">{loading?<Card className={styles.empty}>正在读取冻结版本…</Card>:!data?.results.length?<Card className={styles.empty}><h2>{view==='active'?'暂无冻结版本':'没有已删除版本'}</h2><p>在工作流编辑器保存配置并校验冻结后，完整流程版本会显示在这里。</p></Card>:data.results.map(row=><Card className={styles.timer} key={row.id}><header><div><Badge tone={row.deleted?'neutral':'info'}>{row.deleted?'已删除':'冻结快照'} · r{row.revision}</Badge><h2>{row.title}</h2><p>{row.store_name} · {row.node_count} 个节点 · {new Date(row.created_at).toLocaleString('zh-CN')}</p></div><Button compact onClick={()=>setDialog({row,confirm:false})}>查看流程</Button></header><p>历史运行 {row.run_count} 次 · 未结束 {row.active_runs} 次 · 定时计划 {row.schedule_count} 个（启用 {row.active_schedules} 个）</p><footer><span className={styles.help}>{row.active_runs?'有未结束运行，不能删除':row.active_schedules?'请先暂停引用它的定时器':'删除可恢复，历史证据保留'}</span>{row.deleted?<Button compact disabled={busy} onClick={()=>void change(row,true)}>恢复版本</Button>:<Button compact disabled={busy||!row.can_delete} onClick={()=>setDialog({row,confirm:true})}>删除版本</Button>}</footer></Card>)}</section><footer className="table-footer"><span>共 {data?.count??0} 个版本</span><div><Button compact disabled={loading||page===1} onClick={()=>setPage(n=>n-1)}>上一页</Button><span>第 {page} 页</span><Button compact disabled={loading||!data||page*50>=data.count} onClick={()=>setPage(n=>n+1)}>下一页</Button></div></footer>{dialog&&<ReleaseDialog key={`${dialog.row.id}:${dialog.confirm}`} {...dialog} busy={busy} onClose={()=>setDialog(null)} onDelete={()=>void change(dialog.row)}/>}</div>;
}
