'use client';
import {useEffect,useState} from 'react';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {SelectField} from '@/components/ui/select-field';
import {Switch} from '@/components/ui/switch';
import {backendRequest,type ProductBrief} from '@/lib/workflow/backend-client';
import {ProductTaskFields} from './product-task-fields';
import styles from './live-workflow.module.css';
import {recommendedSelectionDefaults as recommended} from '@/lib/workflow/recommended-defaults';

type Candidate={pid:string;vid?:string;title?:string;status:string;reason:string;suggested_price?:string;landed_cost?:string;shipping_cost?:string;inventory?:number;maximum_days?:number;supply_type?:string;factory_reported_quantity?:number;processing_days?:number;estimated_total_days?:number;supply_warning?:string};
type Task={id:string;status:string;stage:string;query:Record<string,unknown>;candidates:Candidate[];ranked_vids:string[];error:string;log:{stage:string;message:string;at:string}[]};
export function SelectionPanel({onSelect}:{onSelect:(brief:ProductBrief)=>void}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[task,setTask]=useState<Task|null>(null);
 const [query,setQuery]=useState<Record<string,unknown>>({market:'US',requestedCurrency:'USD',categoryId:'',keyword:'',emptyResultPolicy:'pause',limit:recommended.limit,variants_per_product:recommended.variantsPerProduct,minimum_inventory:recommended.minimumInventory,maximum_days:recommended.maximumDeliveryDays,allow_factory_supply:recommended.allowFactorySupply,factory_processing_days:recommended.factoryProcessingDays,factory_sale_limit:recommended.factorySaleLimit,fee_percent:String(recommended.platformFeeRate+recommended.paymentFeeRate+recommended.returnReserveRate),margin_percent:String(recommended.targetContributionRate),tax_reserve_usd:String(recommended.taxReserveUsd),strategy:'landed-cost.v1'});
 const update=(patch:Record<string,unknown>)=>setQuery(q=>({...q,...patch}));
 useEffect(()=>{let active=true;backendRequest<Task[]>('selections').then(rows=>{if(active){setTasks(rows);setTask(rows[0]??null);}}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false};},[]);
 useEffect(()=>{if(!task||!['queued','running'].includes(task.status))return;let active=true;const timer=setInterval(()=>{backendRequest<Task>(`selections/${task.id}`).then(t=>{if(active){setTask(t);setTasks(rows=>rows.map(r=>r.id===t.id?t:r));}}).catch(e=>{if(active)setNotice(e.message);});},2000);return()=>{active=false;clearInterval(timer);};},[task?.id,task?.status]);
 async function execute(fn:()=>Promise<void>){setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 return <Card className={styles.panel}><h2>CJ 真实选品</h2><p className={styles.meta}>商品采集 → 规格与供货来源核验 → 运费试算 → 规则筛选与成本核算 → 商品方案 → 下方审批发布。任务与证据保存在后端，关闭页面不停止执行。</p><p className={styles.meta}>当前策略为受信规则脚本，不是 LLM：按到货成本与时效排序；目标贡献率倒推售价，不预测销量。税费预留和费用率是你的经营假设，不是 CJ 核实税费。当前发布目标支持美国 / USD。</p>
 <Button onClick={()=>setOpen(!open)} aria-expanded={open}>{open?'收起选品参数':'配置真实选品任务'}</Button>
 {open&&<><ProductTaskFields parameters={query} onChange={patch=>{const {category,...rest}=patch;void category;update(rest);}}/><Switch checked={query.allow_factory_supply===true} onCheckedChange={checked=>update({allow_factory_supply:checked})}>允许工厂供货参与选品</Switch><p className={styles.meta}>优先使用 CJ 已验证仓现货。工厂报量不代表已核实现货；工厂供货必须人工确认，即使关闭下方审核开关也不会跳过。</p>{query.allow_factory_supply===true&&<div className={styles.form}>{[['factory_processing_days','工厂备货天数假设（0–60）',0,60],['factory_sale_limit','单规格限售量（1–1000）',1,1000]].map(([key,label,min,max])=><label key={key}>{label}<Input aria-label={String(label)} type="number" min={min} max={max} step="1" value={String(query[key]??'')} onChange={e=>update({[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}<p>可以留空先研究商品与运费；未明确备货天数和限售量的工厂商品不能创建发布方案。这些值是你的假设，不是供应商承诺。</p></div>}<div className={styles.form}>{[
 ['limit','候选商品上限（1–100）',1,100],['variants_per_product','每商品研究规格数（1–20）',1,20],['minimum_inventory','最低供货数量门槛',1,100000],['maximum_days','最长备货＋运输天数',1,90],['fee_percent','平台、支付及退货费用率假设（%）',0,30],['margin_percent','广告前目标贡献率（%）',1,50],['tax_reserve_usd','税费及附加费预留 USD（必填，可明确填 0）',0,10000]
 ].map(([key,label,min,max])=><label key={key}>{label}<Input aria-label={String(label)} type="number" min={min} max={max} step={String(key).includes('percent')||key==='tax_reserve_usd'?'0.01':'1'} value={String(query[key]??'')} onChange={e=>update({[key]:e.target.value===''?null:['limit','variants_per_product','minimum_inventory','maximum_days'].includes(String(key))?Number(e.target.value):e.target.value})}/></label>)}</div><p>最多研究指定数量的商品与规格；未研究的规格明确记录，不算已筛除。</p><Button variant="primary" disabled={busy||!String(query.keyword??"").trim()||!!query.categoryId||(Array.isArray(query.categoryQueries)&&query.categoryQueries.length>0)||query.tax_reserve_usd===null||tasks.some(t=>['queued','running'].includes(t.status))} onClick={()=>void execute(async()=>{const next=await backendRequest<Task>('selections','POST',query);setTask(next);setTasks(rows=>[next,...rows]);setNotice('真实任务已排队；仅查询商品与运费，不采购。');})}>开始真实选品</Button></>}
 {notice&&<p role="status">{notice}</p>}
 {!!tasks.length&&<label>选品记录<SelectField value={task?.id??''} onChange={e=>{const next=tasks.find(t=>t.id===e.target.value);if(next)setTask(next);}}>{tasks.map(t=><option key={t.id} value={t.id}>{t.id.slice(0,8)} · {t.status}</option>)}</SelectField></label>}
 {task&&<><h3>阶段：{task.stage} · {task.status}</h3>{task.error&&<p role="alert">{task.error}</p>}<details><summary>查看执行记录（{task.log.length}）</summary><ol>{task.log.map((entry,i)=><li key={i}>{entry.message}</li>)}</ol></details>{task.candidates.map((row,i)=><Card key={i} className={styles.panel}><strong>{row.title||row.pid}</strong><p>{row.vid} · {row.status} · {row.reason}</p>{row.suggested_price&&<p>建议价 ${row.suggested_price} · 到货成本假设 ${row.landed_cost} · 运费 ${row.shipping_cost} · 运输最长 {row.maximum_days} 天{row.supply_type!=='factory'&&<> · 已验证 CJ 仓库存 {row.inventory}</>}</p>}{row.supply_type==='factory'&&<p>工厂供货 · 报量 {row.factory_reported_quantity}（未核实） · 运营限售 {row.inventory||'未设置'} · 备货 {row.processing_days??'未设置'} 天{row.estimated_total_days!==undefined&&<> · 预计备货＋运输 {row.estimated_total_days} 天</>}。{row.supply_warning}</p>}{task.status==='ready'&&row.status==='eligible'&&<Button disabled={busy} onClick={()=>void execute(async()=>{const result=await backendRequest<{brief:ProductBrief}>(`selections/${task.id}/brief`,'POST',{vid:row.vid});onSelect(result.brief);setNotice('已载入下方商品方案；继续使用原有两轮审批，不自动发布。');})}>使用该规格创建商品方案</Button>}</Card>)}<details><summary>查看本次参数与排序</summary><pre className={styles.json}>{JSON.stringify({query:task.query,ranked_vids:task.ranked_vids},null,2)}</pre></details></>}
 </Card>;
}
