/** Serializable JSON Schema drafts only. Nothing here validates or executes runtime data. */
type Schema = Record<string, unknown>;
const text: Schema = { type: "string", minLength: 1 };
const time: Schema = { type: "string", format: "date-time" };
const list = (items: Schema): Schema => ({ type: "array", items });
const nullable = (schema: Schema): Schema => ({ anyOf: [schema, { type: "null" }] });
const object = (properties: Record<string, Schema>, required = Object.keys(properties)): Schema => ({ type: "object", properties, required, additionalProperties: false });
const money = object({ amount: { type: "string", pattern: "^-?[0-9]+(\\.[0-9]+)?$" }, currency: { type: "string", pattern: "^[A-Z]{3}$" } });
const source = object({ provider: text, observedAt: time, evidenceRef: text, rawRef: nullable(text) });
const channel: Schema = { type: "string", minLength: 2, maxLength: 48, pattern: "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$", description: "已注册销售渠道 ID；注册范围及适配能力由后端另行验证，不限于示例渠道。" };
const observation = object({ kind: { enum: ["observed_retail_price", "search_observation", "verified_demand_metric"] }, value: text, unit: text, source });
const product = object({ productId: text, supplierId: text, title: text, supplierCost: nullable(money), shippingQuote: nullable(money), inventory: nullable({ type: "integer", minimum: 0 }), source, marketObservations: list(observation) });
const artifact = object({ assetRef: text, mimeType: { enum: ["image/png", "image/jpeg", "image/webp"] }, width: { type: "integer", minimum: 1 }, height: { type: "integer", minimum: 1 }, status: { const: "available" }, provenanceRef: text });
const envelope = (id: string, properties: Record<string, Schema>, optional: string[] = []): Schema => ({
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: `urn:commerceos:contract:${id.replace("@", ":")}`,
  title: id,
  description: "可序列化的接口草案；需由后端实现结构及语义校验。example 数据不是实际业务事实。",
  ...object({ schemaVersion: { const: "1" }, ...properties, exampleLabel: text }, ["schemaVersion", ...Object.keys(properties).filter(key=>!optional.includes(key))]),
});

export const contractSchemas: Record<string, Schema> = {
  "ProductImageRequest@1": envelope("ProductImageRequest@1", {productRef:text,referenceAssetRefs:list(text),usage:text,imageCount:{type:'integer',minimum:1,maximum:20}}),
  "ProductImageFacts@1": envelope("ProductImageFacts@1", {productId:text,variantRefs:list(text),factRefs:list(text),referenceAssets:list(artifact),rightsEvidenceRefs:list(text),missingFacts:list(text)}),
  "ProductImagePlan@1": envelope("ProductImagePlan@1", {productId:text,factsRef:text,revision:{type:'integer',minimum:1},immutableClaims:list(text),shots:list(object({purpose:text,prompt:text,width:{type:'integer',minimum:1},height:{type:'integer',minimum:1},referenceAssetRefs:list(text)}))}),
  "GeneratedProductImages@1": envelope("GeneratedProductImages@1", {productId:text,planRef:text,planRevision:{type:'integer',minimum:1},assets:list(artifact),failedShotRefs:list(text)}),
  "CheckedProductImages@1": envelope("CheckedProductImages@1", {productId:text,generatedPackRef:text,checkedAssetRefs:list(text),rejectedAssetRefs:list(text),manualReviewItems:list(text),checkVersion:text}),
  "ApprovedProductImagePack@1": envelope("ApprovedProductImagePack@1", {productId:text,variantRefs:list(text),checkedPackRef:text,revision:{type:'integer',minimum:1},digest:text,approvalRef:text,assets:list(artifact),allowedUses:list(text)}),
  "CampaignBrief@1": envelope("CampaignBrief@1", {productRef:text,market:text,goal:text,imagePackRef:nullable(text),factRefs:list(text)}),
  "CreativePack@1": envelope("CreativePack@1", {briefRef:text,productRef:text,revision:{type:'integer',minimum:1},copyVariants:list(text),assetRefs:list(text),sourcePlanRef:nullable(text)}),
  "ProductQuery@2": envelope("ProductQuery@2", {requestId:text,market:text,categoryId:{type:"string",maxLength:200,description:"兼容旧单类目；使用 categoryQueries 时必须为空。"},categoryQueries:{type:"array",maxItems:10,items:object({categoryId:{type:"string",minLength:1,maxLength:200},keyword:{type:"string",maxLength:200}}),description:"可选扩展；省略保留旧单类目语义，空数组不限类目；非空时全局 keyword 必须为空，ID 唯一，limit 不小于类目数。"},keyword:{type:"string",maxLength:200},candidateSource:{enum:["trending","catalog"],description:"热门子集或全目录匹配；省略保持旧 catalog，不表示官方销量排序。"},emptyResultPolicy:{enum:["pause","drop_keyword_once"]},sourceRef:text,limit:{type:"integer",minimum:1,maximum:1000},requestedCurrency:text},["categoryQueries","candidateSource"]),
  "CJProductFacts@1": envelope("CJProductFacts@1", {
    requestId: text, task: object({market:text,category:text,limit:{type:"integer",minimum:1,maximum:1000},requestedCurrency:text}),
    products:list(object({productId:text,title:text,category:text,source,
      sales90Days:nullable(object({quantity:{type:"integer",minimum:0},windowDays:{const:90},scope:{const:"cj_scope_unconfirmed"},source})),
      variants:list(object({variantId:text,sku:text,options:text,supplierCost:nullable(money),weightGrams:nullable({type:"number",minimum:0}),warehouseCountry:nullable(text),inventory:nullable({type:"integer",minimum:0}),inventoryVerified:nullable({type:"boolean"}),source})),
      missingFields:list(text)})),rejectedRecordRefs:list(text)
  }),
  "EligibleCandidates@1": envelope("EligibleCandidates@1", {factsRef:text,eligibleVariantRefs:list(text),reviewVariantRefs:list(text),exclusions:list(object({variantRef:text,reasons:list(text)}))}),
  "DeliveryCandidates@1": envelope("DeliveryCandidates@1", {candidatesRef:text,market:text,quotes:list(object({variantRef:text,quantity:{type:"integer",minimum:1},originCountry:text,destinationCountry:text,method:text,shippingCost:nullable(money),taxAndDutyCost:nullable(money),maximumTransitDays:nullable({type:"integer",minimum:0}),status:{enum:["estimated","unavailable","insufficient_inputs"]},source})),missingInputs:list(text)}),
  "SelectionProposal@1": envelope("SelectionProposal@1", {deliveryRef:text,productId:text,variantId:text,recommendation:{enum:["shortlist","review","reject"]},suggestedRetailPrice:nullable(money),pricingBasis:list(text),reasons:list(text),evidenceRefs:list(text)}),
  "SelectionAssessment@1": envelope("SelectionAssessment@1", {proposalRef:text,variantId:text,calculationVersion:text,currency:text,retailPrice:nullable(money),supplierCost:nullable(money),shippingCost:nullable(money),taxAndDutyCost:nullable(money),platformFeeRate:{type:"number",minimum:0,maximum:100},paymentFeeRate:{type:"number",minimum:0,maximum:100},returnReserveRate:{type:"number",minimum:0,maximum:100},advertisingCost:nullable(money),contributionBeforeAds:nullable(money),status:{enum:["estimated","insufficient_inputs"]},missingInputs:list(text),calculatedAt:time}),
  "ApprovedProductBrief@2": envelope("ApprovedProductBrief@2", {productId:text,variantId:text,assessmentRef:text,factsRef:text,approvedRevision:{type:"integer",minimum:1},approvalRef:text,allowedChannels:list(channel),market:text,approvedRetailPrice:money,deliveryQuoteRef:text,factualClaims:list(text)}),
  "ApprovedListing@1": envelope("ApprovedListing@1", {validatedListingRef:text,draftRef:text,draftRevision:{type:"integer",minimum:1},draftDigest:text,approvalRef:text,approvedAt:time}),
  "ProductQuery@1": envelope("ProductQuery@1", { requestId: text, market: text, category: text, sourceRef: text, limit: { type: "integer", minimum: 1, maximum: 1000 }, requestedCurrency: { type: "string", pattern: "^[A-Z]{3}$" } }),
  "ProductRecords@1": envelope("ProductRecords@1", { requestId: text, source, records: list(object({ sourceId: text, supplierId: text, title: text, supplierCost: nullable(money), shippingQuote: nullable(money), inventory: nullable({ type: "integer", minimum: 0 }), marketObservations: list(observation), evidenceRef: text, rawCJ: {type:"object",additionalProperties:true,description:"可选 CJ 原始字段，或从 source.rawRef 读取；标准化前不作为规范事实使用。"} }, ["sourceId","supplierId","title","supplierCost","shippingQuote","inventory","marketObservations","evidenceRef"])) }),
  "ProductFacts@1": envelope("ProductFacts@1", { requestId: text, normalizationVersion: text, products: list(product), rejectedRecordRefs: list(text) }),
  "SelectionContext@1": envelope("SelectionContext@1", { requestId: text, items: list(object({ product, calculation: object({ version: text, currency: text, proposedRetailPrice: nullable(money), platformFeeRate: { type: "number", minimum: 0, maximum: 100 }, paymentFeeRate: { type: "number", minimum: 0, maximum: 100 }, returnReserveRate: { type: "number", minimum: 0, maximum: 100 }, estimatedContribution: nullable(money), status: { enum: ["estimated", "insufficient_inputs"] }, missingInputs: list(text), calculatedAt: time }) })) }),
  "ProductDecision@1": envelope("ProductDecision@1", { productId: text, recommendation: { enum: ["shortlist", "review", "reject"] }, score: { type: "number", minimum: 0, maximum: 100 }, reasons: list(text), evidenceRefs: list(text) }),
  "ApprovedProductBrief@1": envelope("ApprovedProductBrief@1", { productId: text, factsRef: text, decisionRef: text, approvedRevision: { type: "integer", minimum: 1 }, approvalRef: text, allowedChannels: list(channel), market: text, approvedRetailPrice: money, factualClaims: list(text) }),
  "ImageBrief@1": envelope("ImageBrief@1", { productId: text, prompt: text, factualEvidenceRefs: list(text), referenceAssetRefs: list(text), providerRef: text, requestedMimeType: { enum: ["image/png", "image/jpeg", "image/webp"] }, width: { type: "integer", minimum: 1 }, height: { type: "integer", minimum: 1 } }),
  "MediaAsset@1": envelope("MediaAsset@1", { productId: text, briefRef: text, asset: artifact, generatedAt: time }),
  "ListingDraft@1": envelope("ListingDraft@1", { productId: text, channel, market: text, locale: text, title: text, body: text, retailPrice: money, factRefs: list(text), assets: list(artifact), pendingImageBriefRefs: list(text), channelAttributes: { type: "object", additionalProperties: true } }),
  "ValidatedListing@1": envelope("ValidatedListing@1", { draftRef: text, channel, validatedRevision: { type: "integer", minimum: 1 }, validationRef: text, validatedAt: time, platformRequirementsVersion: text, status: { const: "valid" } }),
  "PreparedChannelPublication@1": envelope("PreparedChannelPublication@1", { approvedListingRef:text, approvedDigest:text, storeRef:text, connectionVersion:{type:"integer",minimum:1}, mappingPlanRef:text, mappingPlanVersion:text, requestArtifactRef:text, requestDigest:text, checkedAt:time }),
  "PublicationReceipt@1": envelope("PublicationReceipt@1", { productId: text, channel, submissionId: text, idempotencyKey: text, submittedAt: time, status: { enum: ["accepted", "rejected", "processing"] }, issueRefs: list(text), providerReceiptRef: text }),
  "PublishedProduct@1": envelope("PublishedProduct@1", { productId: text, channel, channelListingId: text, submissionRef: text, sellable: { const: true }, confirmedAt: time, confirmationEvidenceRef: text }),
  "OrderContext@1": envelope("OrderContext@1", { orderId: text, channel, paymentState: { enum: ["unknown", "pending", "paid", "refunded"] }, fulfillmentOwner: { enum: ["supplier", "merchant", "platform"] }, fulfillmentEligibility: { enum: ["unknown", "blocked", "eligible"] }, evidenceRefs: list(text) }),
};

const at = "2026-09-30T00:00:00Z";
const exampleSource = { provider: "example-supplier-erp", observedAt: at, evidenceRef: "example://evidence/supplier-quote", rawRef: "example://raw/erp-record" };
const supplierCost = { amount: "18.00", currency: "USD" };
const retail = { amount: "39.00", currency: "USD" };
const sampleProduct = { productId: "demo-product-001", supplierId: "demo-supplier", title: "演示商品", supplierCost, shippingQuote: null, inventory: null, source: exampleSource, marketObservations: [] };
const sampleAsset = { assetRef: "example://assets/demo-generated-image.png", mimeType: "image/png", width: 1200, height: 1200, status: "available", provenanceRef: "example://generation/demo-job" };
const example = (value: Record<string, unknown>, label = "仅前端接口示例；未采集数据、生成图片、批准或发布商品。") => ({ schemaVersion: "1", ...value, exampleLabel: label });
export const contractExamples: Record<string, unknown> = {
  "ProductQuery@2": example({requestId:"demo-query-v2",market:"US",categoryId:"",keyword:"travel organizer",emptyResultPolicy:"pause",sourceRef:"example://connections/cj",limit:20,requestedCurrency:"USD"},"不限类目的关键词任务示例；销售国家不作为 CJ 仓库国家筛选。"),
  "CJProductFacts@1": example({requestId:"demo-request-001",task:{market:"US",category:"home",limit:20,requestedCurrency:"USD"},products:[{productId:"demo-product-001",title:"演示商品",category:"home",source:{...exampleSource,provider:"cj-example"},sales90Days:null,variants:[{variantId:"demo-variant-001",sku:"demo-sku",options:"标准款",supplierCost,weightGrams:null,warehouseCountry:null,inventory:null,inventoryVerified:null,source:exampleSource}],missingFields:["sales90Days","warehouseInventory","weight"]}],rejectedRecordRefs:[]},"CJ 标准化结构示例；销量未知不是零，任务币种不覆盖供货报价币种。"),
  "EligibleCandidates@1": example({factsRef:"example://facts/cj",eligibleVariantRefs:[],reviewVariantRefs:["demo-variant-001"],exclusions:[]},"未知库存进入待复核，不冒充通过库存筛选。"),
  "DeliveryCandidates@1": example({candidatesRef:"example://candidates/independently-verified",market:"US",quotes:[{variantRef:"demo-variant-001",quantity:1,originCountry:"CN",destinationCountry:"US",method:"example-method",shippingCost:null,taxAndDutyCost:null,maximumTransitDays:null,status:"insufficient_inputs",source:exampleSource}],missingInputs:["shippingCost","taxAndDutyCost","transitDays"]},"独立配送契约示例，不代表上述待复核候选已通过。运费不是零，签收时效不是承诺。"),
  "SelectionProposal@1": example({deliveryRef:"example://delivery/quote",productId:"demo-product-001",variantId:"demo-variant-001",recommendation:"review",suggestedRetailPrice:retail,pricingBasis:["仅演示售价假设，需竞品与需求证据"],reasons:["补充库存、销量与配送证据"],evidenceRefs:["example://facts/cj"]}),
  "SelectionAssessment@1": example({proposalRef:"example://proposal/001",variantId:"demo-variant-001",calculationVersion:"1.0.0",currency:"USD",retailPrice:retail,supplierCost,shippingCost:null,taxAndDutyCost:null,platformFeeRate:0,paymentFeeRate:3,returnReserveRate:5,advertisingCost:null,contributionBeforeAds:null,status:"insufficient_inputs",missingInputs:["shippingCost","taxAndDutyCost"],calculatedAt:at},"费用率只是经营假设，缺少配送税费不输出完整贡献值，更不宣称净利润。"),
  "ApprovedProductBrief@2": example({productId:"demo-product-001",variantId:"demo-variant-001",assessmentRef:"example://assessment/independently-complete",factsRef:"example://facts/cj",approvedRevision:1,approvalRef:"example://approval/product",allowedChannels:["shopify"],market:"US",approvedRetailPrice:retail,deliveryQuoteRef:"example://delivery/independently-complete",factualClaims:["独立的已核实描述示例"]},"独立审批契约示例，不表示上述待复核方案获批。实际批准须由后端核验事实和版本。"),
  "ApprovedListing@1": example({validatedListingRef:"example://validation/listing",draftRef:"example://listing/final",draftRevision:1,draftDigest:"example-digest-not-a-real-hash",approvalRef:"example://approval/final-draft",approvedAt:at},"最终草稿审批示例；后端绑定版本和摘要，修改后旧批准失效。"),
  "ProductQuery@1": example({ requestId: "demo-request-001", market: "US", category: "home", sourceRef: "example://connections/supplier-erp", limit: 20, requestedCurrency: "USD" }),
  "ProductRecords@1": example({ requestId: "demo-request-001", source: exampleSource, records: ["001", "002"].map(suffix => ({ sourceId: `source-product-${suffix}`, supplierId: "demo-supplier", title: suffix === "001" ? "演示商品" : "第二个候选商品", supplierCost, shippingQuote: null, inventory: null, marketObservations: [], evidenceRef: "example://evidence/supplier-quote" })) }, "供应ERP报价示例；采购成本不是Amazon零售价，空marketObservations不代表市场需求已验证。"),
  "ProductFacts@1": example({ requestId: "demo-request-001", normalizationVersion: "1.0.0", products: [sampleProduct, { ...sampleProduct, productId: "demo-product-002", title: "第二个候选商品" }], rejectedRecordRefs: [] }, "规范化示例；两个候选完整保留，未知物流和库存保持null，市场证据独立保存。"),
  "SelectionContext@1": example({ requestId: "demo-request-001", items: [{ product: sampleProduct, calculation: { version: "1.0.0", currency: "USD", proposedRetailPrice: retail, platformFeeRate: 15, paymentFeeRate: 3, returnReserveRate: 5, estimatedContribution: null, status: "insufficient_inputs", missingInputs: ["shippingQuote", "applicableTaxAndDuties"], calculatedAt: at } }, { product: { ...sampleProduct, productId: "demo-product-002", title: "第二个候选商品" }, calculation: { version: "1.0.0", currency: "USD", proposedRetailPrice: null, platformFeeRate: 15, paymentFeeRate: 3, returnReserveRate: 5, estimatedContribution: null, status: "insufficient_inputs", missingInputs: ["proposedRetailPrice", "shippingQuote", "applicableTaxAndDuties"], calculatedAt: at } }] }, "批量核算保留所有候选及各自缺失信息；售价是经营假设，缺项不输出已验证毛利。"),
  "ProductDecision@1": example({ productId: "demo-product-001", recommendation: "review", score: 72, reasons: ["补充运费与市场证据后复核"], evidenceRefs: ["example://evidence/supplier-quote"] }),
  "ApprovedProductBrief@1": example({ productId: "demo-product-001", factsRef: "example://facts/product", decisionRef: "example://decisions/product", approvedRevision: 2, approvalRef: "example://approvals/listing-001", allowedChannels: ["shopify"], market: "US", approvedRetailPrice: retail, factualClaims: ["示例中已核实的商品描述"] }, "独立契约形状示例，不是前述待复核商品的实际批准；approvalRef必须由真实授权服务校验。"),
  "ImageBrief@1": example({ productId: "demo-product-001", prompt: "基于获准参考图制作白底商品图，保留实际商品结构。", factualEvidenceRefs: ["example://facts/product"], referenceAssetRefs: ["example://assets/source-photo"], providerRef: "example://connections/image-service", requestedMimeType: "image/png", width: 1200, height: 1200 }, "这是图像制作请求，不包含已生成assetRef。"),
  "MediaAsset@1": example({ productId: "demo-product-001", briefRef: "example://briefs/image-001", asset: sampleAsset, generatedAt: at }, "模拟可用产物的形状；example://引用不是实际图片，真实运行必须确认资产存在和可访问。"),
  "ListingDraft@1": example({ productId: "demo-product-001", channel: "shopify", market: "US", locale: "en-US", title: "Example product", body: "Verified example description.", retailPrice: retail, factRefs: ["example://facts/product"], assets: [], pendingImageBriefRefs: ["example://briefs/image-001"], channelAttributes: {} }, "未完成图片的草稿示例；制作请求放pendingImageBriefRefs，不能冒充assets。"),
  "ValidatedListing@1": example({ draftRef: "example://drafts/completed-listing", channel: "shopify", validatedRevision: 3, validationRef: "example://validations/listing", validatedAt: at, platformRequirementsVersion: "example-policy-version", status: "valid" }, "独立校验结果形状示例，不代表前述未完成素材草稿已通过检查。"),
  "PreparedChannelPublication@1": example({approvedListingRef:"example://approval/final-draft",approvedDigest:"example-approved-digest",storeRef:"example://store",connectionVersion:1,mappingPlanRef:"example://mapping/plan",mappingPlanVersion:"1",requestArtifactRef:"example://prepared/request",requestDigest:"example-request-digest",checkedAt:at},"设计示例，不是实际执行产物。缺必填字段不得输出；请求和批准摘要、店铺及方案版本一并绑定，不包含凭证。"),
  "PublicationReceipt@1": example({ productId: "demo-product-001", channel: "amazon", submissionId: "demo-submission-001", idempotencyKey: "demo-listing-revision-3", submittedAt: at, status: "accepted", issueRefs: [], providerReceiptRef: "example://receipts/listing-001" }, "提交被接受不代表可售；仍需等待异步处理和真实渠道状态。"),
  "PublishedProduct@1": example({ productId: "demo-product-001", channel: "amazon", channelListingId: "demo-listing-001", submissionRef: "example://receipts/listing-001", sellable: true, confirmedAt: at, confirmationEvidenceRef: "example://evidence/channel-buyable" }, "可售状态形状示例；真实运行必须以渠道确认作为依据，不从accepted推断sellable。"),
  "OrderContext@1": example({ orderId: "demo-order-001", channel: "amazon", paymentState: "pending", fulfillmentOwner: "platform", fulfillmentEligibility: "unknown", evidenceRefs: ["example://events/order-001"] }),
};
