'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {PageHeader} from '@/components/app/page-header';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {SelectField} from '@/components/ui/select-field';
import {Input} from '@/components/ui/input';
import {backendRequest,type BackendStore} from '@/lib/workflow/backend-client';
import styles from '../operations/operations-archive.module.css';
import {shipmentLabels,type Shipment} from '@/lib/business';
type Data={products:{id:string;title:string;price:string}[];messages:{id:string;message:string;order_id:string|null}[];records:{id:string;kind:string;created_at:string;payload:Record<string,unknown>}[]};
async function key(){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(crypto.randomUUID()));return Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join('');}
export function TestStoreLab(){
 const [stores,setStores]=useState<BackendStore[]>([]),[store,setStore]=useState(''),[data,setData]=useState<Data|null>(null),[product,setProduct]=useState(''),[order,setOrder]=useState(''),[message,setMessage]=useState('标准配送需要多久？'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [costs,setCosts]=useState<Record<string,string>>({procurement:'',shipping:'',platform_payment:'',advertising:'',other:''});
 const pending=useRef<{signature:string;key:string}|null>(null);
 useEffect(()=>{void backendRequest<BackendStore[]>('stores').then(rows=>{const valid=rows.filter(r=>r.active&&r.verified);setStores(valid);if(valid.length===1)setStore(valid[0].id);}).catch(e=>setError(String(e)));},[]);
 async function load(){const result=await backendRequest<Data>(`stores/${store}/test-lab`);setData(result);}
 async function advance(shipment:Shipment,status:string){setBusy(true);setError('');setNotice('');try{await backendRequest(`stores/${store}/test-lab`,'POST',{action:'test.shipment.advance',data:{shipment_id:shipment.external_id,expected_revision:shipment.revision,status,test_data_confirmed:true}});await load();setNotice('测试物流事件已持久化；原流程将在下一次读取时继续，不表示实体发货。');}catch(e){setError(e instanceof Error?e.message:'物流推进失败');}finally{setBusy(false);}}
 async function run(action:string){setBusy(true);setError('');setNotice('');try{
  if(action==='read'){await load();return;}
  if(action==='sync'){for(const kind of ['orders','customers','finance'])await backendRequest(`stores/${store}/sync/${kind}`,'POST',{});setNotice('订单、物流、客户与财务各同步一页；复盘读取这些已同步记录。');return;}
  const signature=JSON.stringify({store,action,product,costs,order,message});
  if(!pending.current||pending.current.signature!==signature)pending.current={signature,key:await key()};
  const payload=action==='enable'?{confirmed:true}:action==='test.order.create'?{operation_key:pending.current.key,product_id:product,quantity:1,test_data_confirmed:true,...Object.fromEntries(Object.entries(costs).map(([k,v])=>[k,v===''?null:v]))}:{operation_key:pending.current.key,message,order_id:order||null,test_data_confirmed:true};
  await backendRequest(`stores/${store}/test-lab`,'POST',{action,data:payload});pending.current=null;await load();setNotice(action==='enable'?'测试接口已验收，原发布连接版本不变。':'已通过 HTTP 写入测试站数据库。');
 }catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 return <div className={styles.workspace}><PageHeader title="测试站联调中心" description="用真实本机 HTTP 与数据库测试业务，不收款、不采购、不发邮件、不替换线上图片。" actions={<Link className="ui-button" href="/test-store">打开测试独立站 ↗</Link>}/>
 <Card className={styles.panel}><label>复用已接入店铺<SelectField value={store} onChange={e=>{setStore(e.target.value);setData(null);setProduct('');setOrder('');}}><option value="">选择店铺</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</SelectField></label><label className={styles.checkbox}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>确认使用 Northwind 测试政策与虚构客户。测试付款仅用于验证链路，成本未填写保持未知。</label><div className={styles.actions}><Button disabled={!store||!consent||busy} onClick={()=>void run('enable')}>验收并启用测试业务接口</Button><Button disabled={!store||busy} onClick={()=>void run('read')}>读取测试站记录</Button></div>{error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</Card>
 {data&&<><div className={styles.layout}><Card className={styles.panel}><h2>1 · 测试购买</h2><p>选择真正发布到这家店铺的商品。保存固定虚构客户与测试付款事件；不扣减或伪造真实库存。</p><SelectField value={product} onChange={e=>setProduct(e.target.value)}><option value="">选择已上架商品</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.title} · ${p.price}</option>)}</SelectField><details className={styles.evidence}><summary>测试成本（USD） · 可选</summary><div className={styles.form}>{Object.entries({procurement:'采购',shipping:'配送',platform_payment:'支付手续费',advertising:'广告',other:'其他'}).map(([key,label])=><label key={key}>{label}<Input type="number" min="0" step="0.01" value={costs[key]} placeholder="留空为未知，0 为明确无费用" onChange={e=>setCosts(c=>({...c,[key]:e.target.value}))}/></label>)}</div></details><Button disabled={!product||!consent||busy} onClick={()=>void run('test.order.create')}>创建一笔测试购买</Button><Button disabled={busy} onClick={()=>void run('sync')}>同步订单、客户与财务</Button><Link href="/reviews">查看经营复盘 ↗</Link></Card>
 <Card className={styles.panel}><h2>2 · 客户消息</h2><SelectField value={order} onChange={e=>setOrder(e.target.value)}><option value="">不关联订单 · 政策咨询</option>{data.records.filter(r=>r.kind==='order').map(r=><option key={r.id} value={r.id}>测试订单 · {r.id.slice(0,8)}</option>)}</SelectField><div className={styles.form}><label>客户问题<textarea maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label></div><Button disabled={!message.trim()||!consent||busy} onClick={()=>void run('support.receive')}>发送到测试站收件箱</Button><Link href="/support">在客服模块读取并答复 ↗</Link></Card></div>
 <Card className={styles.panel}><h2>订单到交付 · 测试物流</h2><p>先在订单到交付流程选择订单、保存冻结并确认履约。这里仅推进测试运单的来源事件，不调用 CJ 或承运商。</p><Link href="/workflow/builder?template=fulfillment">打开订单到交付流程 ↗</Link>{data.records.filter(r=>r.kind==='shipment').map(r=>{const s=r.payload as unknown as Shipment;return <Card key={r.id} className={styles.panel}><h3>{shipmentLabels[s.status]} · {s.tracking_number}</h3><p>订单 {s.order_id}</p>{s.events.map((e,i)=><p key={i}>{e.description} · {new Date(e.occurred_at).toLocaleString('zh-CN')}</p>)}<div className={styles.actions}>{(s.status==='prepared'?['dispatched']:s.status==='dispatched'?['in_transit','exception']:s.status==='in_transit'?['delivered','exception']:[]).map(status=><Button key={status} disabled={busy||!consent} onClick={()=>void advance(s,status)}>模拟{shipmentLabels[status]}</Button>)}</div></Card>;})}{!data.records.some(r=>r.kind==='shipment')&&<p>尚无测试运单，不能凭时间生成出库或签收。</p>}</Card>
 <Card className={styles.panel}><h2>3 · 商品图交付</h2><p>在商品图流程中生成、检查并确认素材包，再点击“归档到测试站”。这里展示真实接口回执，不会改动原发布商品。</p><Link href="/workflow/builder?template=product-images">打开商品图流程 ↗</Link><h2>已持久化记录</h2>{data.records.map(r=><details key={r.id} className={styles.evidence}><summary>{r.kind==='order'?'测试订单':r.kind==='reply'?'客服答复':'素材归档'} · {new Date(r.created_at).toLocaleString()}</summary><pre className={styles.reply}>{JSON.stringify(r.payload,null,2)}</pre></details>)}{!data.records.length&&<p>暂无记录</p>}<h2>收件箱</h2>{data.messages.map(m=><p key={m.id}>{m.message}</p>)}</Card></>}
 </div>;
}
