# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('document', models.JSONField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skillversion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField()),
                ('document', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skillversion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='workflows.workflowdraft')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workflow', 'revision'), name='unique_workflow_revision')],
            },
        ),
    ]
