# Generated by Django 5.2.17 on 2026-10-03 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_mappingsession_modelconnection'),
        ('identity', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('document', models.JSONField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
        ),
        migrations.CreateModel(
            name='DesignRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField()),
                ('document', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('store_version', models.PositiveIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='design_release', to='workflows.workflowversion')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.workflowdesign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workflowdesign',
            constraint=models.UniqueConstraint(fields=('team', 'client_id'), name='unique_team_design'),
        ),
        migrations.AddConstraint(
            model_name='designrelease',
            constraint=models.UniqueConstraint(fields=('design', 'revision'), name='unique_design_release'),
        ),
    ]
