# Generated by Django 5.2.17 on 2026-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowdesign_designrelease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdesign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
