# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('identity', '0001_initial'),
        ('runtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(max_length=100)),
                ('evidence', models.JSONField()),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='runtime.workflowrun')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='runtime.workflowrun')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='prepared', max_length=20)),
                ('receipt', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='runtime.workflowrun')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'key'), name='unique_external_key')],
            },
        ),
    ]
