'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { SelectField } from '@/components/ui/select-field';
import { featured, productMaterial, type Product } from './catalog';
import { useCart } from './test-provider';
import Storefront from './storefront';
import StoreFooter from './store-footer';
import { TestStore } from '../test-store';
import type { TestOrderAction, TestOrderStatus } from '@/lib/test-store';
const nextActions:Partial<Record<TestOrderStatus,{action:TestOrderAction;label:string}>>={pending:{action:'pay',label:'模拟付款成功'},paid:{action:'authorize',label:'确认测试履约权限'},authorized:{action:'dispatch',label:'模拟提交 CJ 履约'},dispatch_requested:{action:'ship',label:'模拟收到出库事件'},shipped:{action:'notify',label:'记录模拟发货邮件'},notified:{action:'deliver',label:'模拟收到签收事件'}};
function TestBanner(){return <aside className="test-banner"><span>TEST SNAPSHOT · 不真实收款／发货</span><Link href="/test-store/checkout">测试订单</Link><Link href="/workflow/builder">工作台</Link></aside>;}
function Header(){const {count}=useCart();return <><div className="announcement">NEW YORK ATELIER · EDITION 04 · LOCAL TEST STORE</div><header className="site-header inner-header"><Link className="brand" href="/test-store">CROWNLEY<small>NEW YORK</small></Link><nav className="desktop-nav">{['Clothing','Shoes','Bags','Hats'].map(c=><Link key={c} href={`/test-store/collections/${c.toLowerCase()}`}>{c}</Link>)}</nav><div className="header-actions"><Link href="/test-store/search">Search</Link><Link href="/test-store/cart">Bag ({count})</Link></div></header></>;}
function ProductCard({product}:{product:Product}){return <article className="product-card"><div className="product-image"><Link href={`/test-store/products/${product.id}`}><img src={product.image} alt={product.name} loading="lazy"/></Link>{product.badge&&<span>{product.badge}</span>}<Link className="quick-view" href={`/test-store/products/${product.id}`}>Explore the piece ↗</Link></div><div className="product-info"><div><Link href={`/test-store/products/${product.id}`}>{product.name}</Link><small>{product.color} · {productMaterial(product)}</small></div><strong>${product.price}</strong></div></article>;}
function TestLab(){const {products,notice,backendStatus}=useCart();return <details className="test-lab"><summary>运营测试台 / 数据来源与测试边界</summary><p>前端结构与样式取自 Crownley，商品是公开页面的固定快照；图片与展示价格不代表实时 CJ 库存、报价或订单证据。所有账户、支付、订阅、采购、物流、邮件及追踪服务均未连接。购物车与模拟订单刷新重置；工作流发布的商品由 Django 持久化，测试信息不会发往原站。</p><p>测试站已提供发布与可售查询接口，可通过后端实运行页面完成两轮审批后发布；购物、支付与交付仍为模拟。原 FORM 测试夹具保留在 <Link href="/test-store/legacy">旧测试站</Link>，可验证草稿模拟上架。</p><p>{backendStatus}</p><Link href="/workflow/live">进入后端实运行 ↗</Link><p>当前商品 {products.length} 件商品。不会请求真实商品采集或营销接口。</p><p role="status">{notice}</p></details>;}
export function CrownleyHome(){const {products}=useCart();return <><Storefront products={products.filter(p=>p.status==='Active')} featured={featured.flatMap(f=>{const product=products.find(p=>p.id===f.product.id&&p.status==='Active');return product?[{...f,product}]:[];})}/><TestLab/><TestBanner/></>;}
function ProductDetail({product}:{product:Product}){const {addItem,notice}=useCart();const sizes=Object.keys(product.sizeStock??{});const options=sizes.length?sizes:product.department==='Clothing'?['S','M','L']:['One Size'];const [size,setSize]=useState(options[0]);const [image,setImage]=useState(product.image);return <><div className="breadcrumbs"><Link href="/test-store">Home</Link><span>/</span><span>{product.department}</span><span>/</span><b>{product.name}</b></div><section className="product-detail"><div className="test-gallery"><img src={image} alt={product.name}/><div className="test-controls">{[product.image,...(product.gallery??[]).slice(0,3)].map((src,i)=><Button key={src} compact aria-pressed={image===src} onClick={()=>setImage(src)}>Photo {i+1}</Button>)}</div></div><div className="detail-copy"><p className="eyebrow dark">CROWNLEY ATELIER</p><h1>{product.name}</h1><strong className="detail-price">${product.price}</strong><p className="detail-tax">Test pricing · No payment collected.</p><p className="detail-description">{product.description}</p><label>Size<SelectField aria-label="Product size" value={size} onChange={e=>setSize(e.target.value)}>{options.map(s=><option key={s}>{s}</option>)}</SelectField></label><div className="test-controls"><Button variant="primary" disabled={!product.stock} onClick={()=>addItem(product,1,size)}>Add to bag</Button><Link className="button dark" href="/test-store/cart">View bag →</Link></div><p role="status">{notice}</p><div className="detail-accordions"><details open><summary>Details & composition</summary><p>{product.category} · {product.color}. Material claims must be confirmed with the supplier; this is a display snapshot.</p></details><details><summary>Shipping & returns</summary><p>No real delivery or return service. Use the operator test controls to simulate events.</p></details></div></div></section></>;}
function CartPage(){const {items,count,total,updateQuantity}=useCart();return <section className="cart-page"><h1>Your bag</h1>{!count?<div className="empty-cart-page"><p>Your bag is waiting.</p><Link className="button dark" href="/test-store">Continue shopping</Link></div>:<div className="cart-layout"><div>{items.map(i=><div className="test-cart-row" key={i.lineId}><img src={i.image} alt=""/><p>{i.name}<br/><small>{i.size} · ${i.price}</small></p><Button compact aria-label={`Decrease ${i.name}`} onClick={()=>updateQuantity(i.lineId,i.quantity-1)}>−</Button><span>{i.quantity}</span><Button compact aria-label={`Increase ${i.name}`} onClick={()=>updateQuantity(i.lineId,i.quantity+1)}>+</Button></div>)}</div><div className="order-summary"><h2>Order summary</h2><p>Subtotal · ${total.toFixed(2)}</p><p>Simulation only · shipping and tax $0.00, not a live quote.</p><Link className="button dark" href="/test-store/checkout">Continue to test checkout →</Link></div></div>}</section>;}
function CheckoutPage(){const {items,total,order,placeOrder,advance,notice}=useCart();const [downloadNotice,setDownloadNotice]=useState('');const active=order&&!['delivered','cancelled'].includes(order.status);function exportEvents(){if(!order)return;const url=URL.createObjectURL(new Blob([JSON.stringify({mode:'local-simulation',store:'Crownley-test',order},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${order.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloadNotice('测试事件已导出。');}return <section className="cart-page"><p className="eyebrow dark">LOCAL TEST CHECKOUT</p><h1>{active?'Your test order':'Checkout, without a charge.'}</h1><div className="test-panels"><Card><h2>Fixed test identity</h2><p>Demo Customer<br/>demo@example.invalid<br/>United States · 固定测试地址</p><p>不收集真实姓名、信用卡、邮箱或地址。模拟运费与税费均为零，不是真实报价。</p>{!active&&items.map(i=><p key={i.lineId}>{i.name} × {i.quantity}</p>)}{!active&&<><p>Total · ${total.toFixed(2)}</p><Button variant="primary" disabled={!items.length} onClick={placeOrder}>创建测试订单（不扣款）</Button></>}</Card><Card><h2>{order?order.id:'Test event log'}</h2>{order?<><p>State · <strong>{order.status}</strong></p>{order.items.map(i=><p key={i.productId}>{i.title} × {i.quantity}</p>)}<p>Order total · ${(order.totalCents/100).toFixed(2)}</p><div className="test-controls">{nextActions[order.status]&&<Button variant="primary" onClick={()=>advance(nextActions[order.status]!.action)}>{nextActions[order.status]!.label}</Button>}{order.status==='pending'&&<Button onClick={()=>advance('cancel')}>取消未付款测试订单</Button>}</div>{['notified','delivered'].includes(order.status)&&<p>模拟邮件：订单 {order.id} 已出库。To: demo@example.invalid · 未发送。</p>}<ol>{order.events.map(e=><li key={e.type}><code>{e.type}</code></li>)}</ol><Button onClick={exportEvents}>导出测试事件 JSON</Button><p>{downloadNotice}</p></>:<p>创建订单后，手动模拟付款、授权、CJ 履约、出库、邮件与签收。等待状态不会自动推进，也不投递到工作流引擎。</p>}</Card></div><p role="status">{notice}</p></section>;}
export function CrownleyPage({slug}:{slug:string[]}){const {products}=useCart();const [search,setSearch]=useState('');if(slug[0]==='legacy')return <TestStore/>;const product=slug[0]==='products'?products.find(p=>p.id===slug[1]&&p.status==='Active'):undefined;const category=slug[0]==='collections'?slug[1]:undefined;const shown=products.filter(p=>p.status==='Active'&&(!category||category==='new-arrivals'||p.department?.toLowerCase()===category)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())));return <><Header/>{product?<ProductDetail key={product.id} product={product}/>:slug[0]==='products'?<section className="catalog-empty"><h1>Product unavailable</h1><Link href="/test-store">Return to collection</Link></section>:['checkout','track','support'].includes(slug[0])?<CheckoutPage/>:slug[0]==='cart'?<CartPage/>:['collections','search'].includes(slug[0])?<><section className="collection-hero"><p className="eyebrow dark">THE CROWNLEY EDIT</p><h1>{slug[0]==='search'?'Search the collection':category==='new-arrivals'?'The new edition':category}</h1>{slug[0]==='search'&&<div className="test-search"><Input autoFocus aria-label="Search products" placeholder="Search clothing, shoes, bags or hats" value={search} onChange={e=>setSearch(e.target.value)}/></div>}</section><section className="catalog-section"><p>{shown.length} pieces · test snapshot</p><div className="product-grid home-product-grid">{shown.map(p=><ProductCard key={p.id} product={p}/>)}</div></section></>:<section className="content-hero"><p className="eyebrow dark">CROWNLEY · TEST EDITION</p><h1>{slug.at(-1)?.replaceAll('-',' ')}</h1><p>这是测试站的静态说明入口，不提供真实客服、订阅、隐私授权、订单追踪或售后操作。正式政策与服务需后续配置。</p><Link className="text-link" href="/test-store">Explore the collection →</Link></section>}<StoreFooter/><TestLab/><TestBanner/></>;}
