# Generated by Django 5.2.17 on 2026-10-07 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_id', models.UUIDField(db_index=True)),
                ('idempotency_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('configuration', models.JSONField()),
                ('products', models.JSONField()),
                ('plans', models.JSONField(default=list)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='planning_queued', max_length=30)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('events', models.JSONField(default=list)),
                ('pack', models.JSONField(default=dict)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_index', models.PositiveIntegerField()),
                ('shot_index', models.PositiveIntegerField()),
                ('content', models.BinaryField()),
                ('digest', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('provider_request_id', models.CharField(blank=True, max_length=120)),
                ('usage', models.JSONField(default=dict)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='agents.productimagebatch')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productimagebatch',
            constraint=models.UniqueConstraint(fields=('team', 'idempotency_key'), name='unique_image_batch_key'),
        ),
        migrations.AddConstraint(
            model_name='productimageasset',
            constraint=models.UniqueConstraint(fields=('batch', 'product_index', 'shot_index'), name='unique_image_shot'),
        ),
    ]
