# Generated by Django 5.2.17 on 2026-10-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_productimagebatch_productimageasset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagebatch',
            name='design_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
