# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('runtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(max_length=20)),
                ('generation', models.PositiveIntegerField()),
                ('run_revision', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='runtime.workflowrun')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=1000)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='approvals.approvalrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
