# Generated by Django 5.2.17 on 2026-10-03 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0003_mappingsession_modelconnection'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFinancialFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_order_id', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField()),
                ('source_event_id', models.CharField(max_length=160)),
                ('source_ref', models.CharField(max_length=500)),
                ('paid_at', models.DateTimeField()),
                ('observed_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('paid_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_collected', models.DecimalField(decimal_places=2, max_digits=16)),
                ('refund_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_refunded', models.DecimalField(decimal_places=2, max_digits=16)),
                ('procurement', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('platform_payment', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('advertising', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('other', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'currency', 'paid_at'], name='finance_daily_lookup')],
                'constraints': [models.UniqueConstraint(fields=('store', 'external_order_id', 'revision'), name='finance_order_revision'), models.UniqueConstraint(fields=('store', 'source_event_id'), name='finance_source_event')],
            },
        ),
    ]
