# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('storefront_id', models.UUIDField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(max_length=100)),
                ('operation_key', models.CharField(max_length=100)),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teststore.apiclient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'operation_key'), name='unique_store_operation'), models.UniqueConstraint(fields=('client', 'product_id'), name='unique_store_product')],
            },
        ),
    ]
