# Generated by Django 5.2.17 on 2026-10-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teststore', '0002_publishedproduct_unpublish_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teststore.apiclient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'kind', 'external_id', 'revision'), name='store_business_event')],
            },
        ),
    ]
