# Generated by Django 5.2.17 on 2026-10-07 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_mappingsession_modelconnection'),
        ('teststore', '0003_businessevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_version', models.PositiveIntegerField()),
                ('contract_digest', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=30)),
                ('operation_key', models.CharField(max_length=64)),
                ('input_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teststore.apiclient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'operation_key'), name='unique_test_exchange_key')],
            },
        ),
    ]
