# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=40)),
                ('handler', models.CharField(max_length=100)),
                ('artifact_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('revoked', 'revoked')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'key', 'version'), name='unique_skill_version')],
            },
        ),
    ]
