# Generated by Django 5.2.17 on 2026-10-04 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0003_mappingsession_modelconnection'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('observed_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'kind', 'external_id'), name='commerce_store_record')],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=20)),
                ('cursor', models.CharField(default='0', max_length=200)),
                ('store_version', models.PositiveIntegerField()),
                ('has_more', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'kind'), name='commerce_sync_state')],
            },
        ),
    ]
