# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(default='test-store', max_length=80)),
                ('environment', models.CharField(default='test', max_length=20)),
                ('adapter', models.CharField(default='test-store.v1', max_length=80)),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('credential_ciphertext', models.TextField(blank=True)),
                ('capabilities', models.JSONField(default=list)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
