# Generated by Django 5.2.17 on 2026-10-02 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(default='cj', max_length=40)),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('credential_ciphertext', models.TextField()),
                ('token_ciphertext', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='saved', max_length=20)),
                ('verified_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('sample_products', models.JSONField(default=list)),
                ('verification_token', models.UUIDField(null=True)),
                ('verification_until', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'provider'), name='unique_team_supplier')],
            },
        ),
    ]
