# Generated by Django 5.2.17 on 2026-10-02 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_supplierconnection'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('contract', models.JSONField()),
                ('messages', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('busy_until', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
                ('protocol', models.CharField(max_length=40)),
                ('base_url', models.URLField(max_length=300)),
                ('model_id', models.CharField(max_length=120)),
                ('credential_ciphertext', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
