# Generated by Django 5.2.17 on 2026-10-02 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('identity', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_version', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=30)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('context', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.workflowversion')),
            ],
        ),
        migrations.CreateModel(
            name='WaitCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=30)),
                ('generation', models.PositiveIntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waits', to='runtime.workflowrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='runtime.workflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('available_at', models.DateTimeField()),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runtime.workflowrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.CharField(max_length=100)),
                ('generation', models.PositiveIntegerField()),
                ('status', models.CharField(default='running', max_length=30)),
                ('input_digest', models.CharField(max_length=64)),
                ('output', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='runtime.workflowrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='workflowrun',
            constraint=models.UniqueConstraint(fields=('team', 'idempotency_key'), name='unique_run_key'),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_event_sequence'),
        ),
    ]
