# Generated by Django 5.2.17 on 2026-10-02 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('runtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.JSONField()),
                ('connection_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='queued', max_length=30)),
                ('stage', models.CharField(default='collect', max_length=30)),
                ('evidence', models.JSONField(default=dict)),
                ('candidates', models.JSONField(default=list)),
                ('log', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
