# Generated by Django 5.2.17 on 2026-10-03 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('runtime', '0002_selection_tasks'),
        ('workflows', '0003_workflowdesign_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=100)),
                ('clock', models.CharField(default='09:00', max_length=5)),
                ('weekdays', models.JSONField(default=list)),
                ('interval_hours', models.PositiveIntegerField(default=24)),
                ('enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('next_due_at', models.DateTimeField(db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='runtime.workflowrun')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.designrelease')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('schedule_revision', models.PositiveIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.designrelease')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='runtime.workflowrun')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='runtime.workflowschedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'scheduled_at'), name='unique_schedule_occurrence')],
            },
        ),
    ]
