# Generated by Django 5.2.17 on 2026-10-07 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_mappingsession_modelconnection'),
        ('identity', '0001_initial'),
        ('runtime', '0003_schedulerheartbeat_workflowschedule_and_more'),
        ('workflows', '0005_business_profile_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowschedule',
            name='last_polled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workflowschedule',
            name='message_cursor',
            field=models.UUIDField(null=True),
        ),
        migrations.CreateModel(
            name='SupportMessageClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_version', models.PositiveIntegerField()),
                ('message_id', models.UUIDField()),
                ('message', models.JSONField(default=dict)),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workflows.designrelease')),
                ('run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='runtime.workflowrun')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_claims', to='runtime.workflowschedule')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connections.store')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'store', 'store_version', 'message_id'), name='unique_support_message_claim')],
            },
        ),
    ]
